services:
  bot:
    build: .
    container_name: gamer_bot
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    # Mapeie apenas a pasta de dados se o bot salvar algo permanente
    volumes:
      - ./data:/app/data